//! ZeroBus sink for integrating with Databricks via Protobuf serialization.
//!
//! This module provides:
//! - The generated `CertRecord` protobuf message (compiled from `proto/cert_record.proto`)
//! - Conversion from `DeltaCertRecord` to `CertRecord`
//! - DescriptorProto extraction for ZeroBus SDK integration

use crate::delta_sink::DeltaCertRecord;
use prost::Message;

/// Re-export the generated protobuf code from prost-build.
pub mod proto {
    include!(concat!(env!("OUT_DIR"), "/certstream.rs"));
}

/// Convert a `DeltaCertRecord` reference to a `CertRecord`.
///
/// This conversion maps all 20 fields from the internal Delta format to the protobuf message.
/// String fields are cloned to owned `String` values, and scalar fields are directly assigned.
impl proto::CertRecord {
    pub fn from_delta_cert(record: &DeltaCertRecord) -> Self {
        Self {
            cert_index: record.cert_index,
            update_type: record.update_type.clone(),
            seen: record.seen,
            seen_date: record.seen_date.clone(),
            source_name: record.source_name.clone(),
            source_url: record.source_url.clone(),
            cert_link: record.cert_link.clone(),
            serial_number: record.serial_number.clone(),
            fingerprint: record.fingerprint.clone(),
            sha256: record.sha256.clone(),
            sha1: record.sha1.clone(),
            not_before: record.not_before,
            not_after: record.not_after,
            is_ca: record.is_ca,
            signature_algorithm: record.signature_algorithm.clone(),
            subject_aggregated: record.subject_aggregated.clone(),
            issuer_aggregated: record.issuer_aggregated.clone(),
            all_domains: record.all_domains.clone(),
            as_der: record.as_der.clone(),
            chain: record.chain.clone(),
        }
    }
}

/// Extract the DescriptorProto for the CertRecord message from the compiled file descriptor set.
///
/// This function decodes the binary file descriptor set generated by prost-build at compile time
/// and returns the DescriptorProto for the CertRecord message. This descriptor is suitable for
/// use with the ZeroBus SDK's `TableProperties` for Databricks table registration.
///
/// # Panics
///
/// Panics if:
/// - The descriptor bytes cannot be decoded as a `FileDescriptorSet`
/// - The file descriptor set is empty
/// - The file descriptor set contains no message types
pub fn cert_record_descriptor_proto() -> prost_types::DescriptorProto {
    let descriptor_bytes = include_bytes!(concat!(
        env!("OUT_DIR"),
        "/cert_record_descriptor.bin"
    ));
    let file_descriptor_set =
        prost_types::FileDescriptorSet::decode(&descriptor_bytes[..])
            .expect("Failed to decode file descriptor set");
    file_descriptor_set
        .file
        .into_iter()
        .next()
        .expect("No file descriptors in set")
        .message_type
        .into_iter()
        .next()
        .expect("No message types in file descriptor")
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Helper function to create a test `DeltaCertRecord` with deterministic values.
    fn make_test_record() -> DeltaCertRecord {
        DeltaCertRecord {
            cert_index: 12345,
            update_type: "X509AddedToSCT".to_string(),
            seen: 1708454400.5,
            seen_date: "2024-02-20".to_string(),
            source_name: "google".to_string(),
            source_url: "https://ct.googleapis.com/logs/argon2024/".to_string(),
            cert_link: "https://ct.googleapis.com/logs/argon2024/?d=12345".to_string(),
            serial_number: "deadbeef".to_string(),
            fingerprint: "abc123def456".to_string(),
            sha256: "sha256hash".to_string(),
            sha1: "sha1hash".to_string(),
            not_before: 1700000000,
            not_after: 1731536000,
            is_ca: false,
            signature_algorithm: "sha256WithRSAEncryption".to_string(),
            subject_aggregated: "CN=example.com".to_string(),
            issuer_aggregated: "CN=Let's Encrypt".to_string(),
            all_domains: vec!["example.com".to_string(), "www.example.com".to_string()],
            as_der: "base64_encoded_der_data".to_string(),
            chain: vec!["cert1".to_string(), "cert2".to_string()],
        }
    }

    #[test]
    fn test_from_delta_cert_all_fields() {
        let delta_record = make_test_record();
        let cert_record = proto::CertRecord::from_delta_cert(&delta_record);

        // Verify all 20 fields match
        assert_eq!(cert_record.cert_index, 12345);
        assert_eq!(cert_record.update_type, "X509AddedToSCT");
        assert_eq!(cert_record.seen, 1708454400.5);
        assert_eq!(cert_record.seen_date, "2024-02-20");
        assert_eq!(cert_record.source_name, "google");
        assert_eq!(cert_record.source_url, "https://ct.googleapis.com/logs/argon2024/");
        assert_eq!(
            cert_record.cert_link,
            "https://ct.googleapis.com/logs/argon2024/?d=12345"
        );
        assert_eq!(cert_record.serial_number, "deadbeef");
        assert_eq!(cert_record.fingerprint, "abc123def456");
        assert_eq!(cert_record.sha256, "sha256hash");
        assert_eq!(cert_record.sha1, "sha1hash");
        assert_eq!(cert_record.not_before, 1700000000);
        assert_eq!(cert_record.not_after, 1731536000);
        assert!(!cert_record.is_ca);
        assert_eq!(cert_record.signature_algorithm, "sha256WithRSAEncryption");
        assert_eq!(cert_record.subject_aggregated, "CN=example.com");
        assert_eq!(cert_record.issuer_aggregated, "CN=Let's Encrypt");
        assert_eq!(
            cert_record.all_domains,
            vec!["example.com", "www.example.com"]
        );
        assert_eq!(cert_record.as_der, "base64_encoded_der_data");
        assert_eq!(cert_record.chain, vec!["cert1", "cert2"]);
    }

    #[test]
    fn test_from_delta_cert_scalar_fields() {
        let delta_record = DeltaCertRecord {
            cert_index: 99999,
            not_before: -1000,
            not_after: 2000000000,
            is_ca: true,
            seen: 0.0,
            ..make_test_record()
        };
        let cert_record = proto::CertRecord::from_delta_cert(&delta_record);

        // Verify scalar field conversions
        assert_eq!(cert_record.cert_index, 99999);
        assert_eq!(cert_record.not_before, -1000);
        assert_eq!(cert_record.not_after, 2000000000);
        assert!(cert_record.is_ca);
        assert_eq!(cert_record.seen, 0.0);
    }

    #[test]
    fn test_from_delta_cert_repeated_string_fields() {
        let delta_record = DeltaCertRecord {
            all_domains: vec![
                "a.example.com".to_string(),
                "b.example.com".to_string(),
                "c.example.com".to_string(),
            ],
            chain: vec!["root".to_string(), "intermediate".to_string(), "leaf".to_string()],
            ..make_test_record()
        };
        let cert_record = proto::CertRecord::from_delta_cert(&delta_record);

        assert_eq!(
            cert_record.all_domains,
            vec!["a.example.com", "b.example.com", "c.example.com"]
        );
        assert_eq!(cert_record.chain, vec!["root", "intermediate", "leaf"]);
    }

    #[test]
    fn test_cert_record_descriptor_proto() {
        let descriptor = cert_record_descriptor_proto();

        // Verify basic descriptor properties
        assert_eq!(descriptor.name, Some("CertRecord".to_string()));

        // Count the fields in the descriptor
        let field_count = descriptor.field.len();
        assert_eq!(field_count, 20, "CertRecord should have exactly 20 fields");

        // Verify field names and numbers (spot check)
        let fields_map: std::collections::HashMap<&str, i32> = descriptor
            .field
            .iter()
            .map(|f| (f.name.as_deref().unwrap_or(""), f.number.unwrap_or(0)))
            .collect();

        assert_eq!(*fields_map.get("cert_index").unwrap(), 1);
        assert_eq!(*fields_map.get("update_type").unwrap(), 2);
        assert_eq!(*fields_map.get("seen").unwrap(), 3);
        assert_eq!(*fields_map.get("is_ca").unwrap(), 14);
        assert_eq!(*fields_map.get("chain").unwrap(), 20);
    }

    #[test]
    fn test_cert_record_round_trip() {
        let delta_record = make_test_record();
        let cert_record = proto::CertRecord::from_delta_cert(&delta_record);

        // Encode to bytes
        let encoded = cert_record.encode_to_vec();
        assert!(!encoded.is_empty());

        // Decode back
        let decoded = proto::CertRecord::decode(&encoded[..])
            .expect("Failed to decode CertRecord");

        // Verify all fields survive the round-trip
        assert_eq!(decoded.cert_index, cert_record.cert_index);
        assert_eq!(decoded.update_type, cert_record.update_type);
        assert_eq!(decoded.seen, cert_record.seen);
        assert_eq!(decoded.seen_date, cert_record.seen_date);
        assert_eq!(decoded.source_name, cert_record.source_name);
        assert_eq!(decoded.source_url, cert_record.source_url);
        assert_eq!(decoded.cert_link, cert_record.cert_link);
        assert_eq!(decoded.serial_number, cert_record.serial_number);
        assert_eq!(decoded.fingerprint, cert_record.fingerprint);
        assert_eq!(decoded.sha256, cert_record.sha256);
        assert_eq!(decoded.sha1, cert_record.sha1);
        assert_eq!(decoded.not_before, cert_record.not_before);
        assert_eq!(decoded.not_after, cert_record.not_after);
        assert_eq!(decoded.is_ca, cert_record.is_ca);
        assert_eq!(decoded.signature_algorithm, cert_record.signature_algorithm);
        assert_eq!(decoded.subject_aggregated, cert_record.subject_aggregated);
        assert_eq!(decoded.issuer_aggregated, cert_record.issuer_aggregated);
        assert_eq!(decoded.all_domains, cert_record.all_domains);
        assert_eq!(decoded.as_der, cert_record.as_der);
        assert_eq!(decoded.chain, cert_record.chain);
    }
}
